const vrag = {
  list: [
    {
      id: 1,
      name: "Слизень",
      hp: 20,
      maxHp: 20,
      atk: 4,
      def: 2,
      xpDrop: 3,
      drop: ["слизь"],
    },
    {
      id: 3,
      name: "Разбойник плут",
      hp: 50,
      maxHp: 50,
      atk: 10,
      def: 5,
      xpDrop: 8,
      drop: ["кинжал"],
    },
    {
      id: 4,
      name: "Разбойник воин",
      hp: 45,
      maxHp: 45,
      atk: 13,
      def: 6,
      xpDrop: 10,
      drop: ["мечь"],
    },
    {
      id: 5,
      name: "Разбойник охотник",
      hp: 50,
      maxHp: 50,
      atk: 7,
      def: 5,
      xpDrop: 7,
      drop: ["лук"],
    },
    {
      id: 3.3,
      name: "Разбойник плут (элитный)",
      hp: 50,
      maxHp: 50,
      atk: 10,
      def: 5,
      xpDrop: 9,
      drop: ["кинжал"],
    },
    {
      id: 6,
      name: "Рыцарь смерти",
      hp: 150,
      maxHp: 150,
      atk: 25,
      def: 15,
      xpDrop: 40,
      drop: ["тяжелый доспех", "тежолый мечь"],
    },
    {
      id: 2,
      name: "Гоблин",
      hp: 40,
      maxHp: 40,
      atk: 7,
      def: 3,
      xpDrop: 5,
      drop: ["монета", "дубинка"],
    },
    {
      id: 7,
      name: "Мимик",
      hp: 100,
      maxHp: 100,
      atk: 10,
      def: 20,
      xpDrop: 20,
      drop: ["золото", "сундук"],
    },
  ],
};

if (typeof module !== "undefined") module.exports = vrag;
