const vrag = {
  list: {
    
    Слизень: {
      name: "Слизень",
      hp: 20,
      maxHp: 20,
      atk: 4,
      def: 2,
      xpDrop: 3,
      drop: ["слизь"],
    },
    Гоблин: {
      name: "Гоблин",
      hp: 40,
      maxHp: 40,
      atk: 7,
      def: 3,
      xpDrop: 5,
      drop: ["дубинка", "ухо гоблина"],
    },
    Разбойник_плут: {
      name: "Разбойник плут",
      hp: 50,
      maxHp: 50,
      atk: 10,
      def: 5,
      xpDrop: 8,
      drop: ["Золото", 10],
    },
    Разбойник_воин: {
      name: "Разбойник воин",
      hp: 45,
      maxHp: 45,
      atk: 13,
      def: 6,
      xpDrop: 10,
      drop: ["Золото", 10],
    },
    Разбойник_охотник: {
      name: "Разбойник охотник",
      hp: 50,
      maxHp: 50,
      atk: 7,
      def: 5,
      xpDrop: 7,
      drop: ["Золото", 10],
    },
    Орк: {
      name: "Орк",
      hp: 70,
      maxHp: 70,
      atk: 18,
      def: 10,
      xpDrop: 15,
      drop: ["орочий амулет"],
    },
    Мимик: {
      name: "Мимик",
      hp: 100,
      maxHp: 100,
      atk: 10,
      def: 20,
      xpDrop: 20,
      drop: ["золото", "сундук"],
    },
    Гарпия: {
      name: "Гарпия",
      hp: 45,
      maxHp: 45,
      atk: 15,
      def: 5,
      xpDrop: 12,
      drop: ["перо гарпии"],
    },
    Минотавр: {
      name: "Минотавр",
      hp: 120,
      maxHp: 120,
      atk: 25,
      def: 15,
      xpDrop: 30,
      drop: ["рог минотавра"],
    },
    Кобальт: {
      name: "Кобальт",
      hp: 35,
      maxHp: 35,
      atk: 8,
      def: 4,
      xpDrop: 6,
      drop: ["чешуя кобальта"],
    },
    Агрессивный_искатель: {
      name: "Агрессивный искатель",
      hp: 80,
      maxHp: 80,
      atk: 20,
      def: 12,
      xpDrop: 25,
      drop: ["старый дневник"],
    },
    Скелет: {
      name: "Скелет",
      hp: 60,
      maxHp: 60,
      atk: 15,
      def: 8,
      xpDrop: 15,
      drop: ["кость", "ржавый щит"],
    },
    Лич: {
      name: "Лич",
      hp: 110,
      maxHp: 110,
      atk: 30,
      def: 10,
      xpDrop: 40,
      drop: ["магическая сфера"],
    },
    Рыцарь_смерти: {
      name: "Рыцарь смерти",
      hp: 250,
      maxHp: 250,
      atk: 45,
      def: 25,
      xpDrop: 150,
      drop: ["тяжелый доспех", "тяжелый меч"],
    }
    },
},


if (typeof module !== "undefined") module.exports = vrag;
