const vrag = {
  
  слизень: {
    name: "Слизень",
    hp: 20,
    MaxHp: 20,
    atk: 4,
    def: 2,
    xpDrop: 3,
    drop: ["слизь"],
  },
  гоблин: {
    name: "Гоблин",
    hp: 40,
    MaxHp: 40,
    atk: 7,
    def: 3,
    xpDrop: 5,
    drop: ["дубинка", "ухо гоблина"],
  },
  разбойник_плут: {
    name: "Разбойник плут",
    hp: 50,
    MaxHp: 50,
    atk: 10,
    def: 5,
    xpDrop: 8,
    drop: ["Золото", 10], //придмет количество
  },
  разбойник_элитный: {
    name: "Разбойник элитный",
    hp: 75,
    MaxHp: 75,
    atk: 25,
    def: 7,
    xpDrop: 14,
    drop: ["Золото", 20],
  },
  разбойник_воин: {
    name: "Разбойник воин",
    hp: 45,
    MaxHp: 45,
    atk: 13,
    def: 6,
    xpDrop: 10,
    drop: ["Золото", 10],
  },
  разбойник_охотник: {
    name: "Разбойник охотник",
    hp: 50,
    MaxHp: 50,
    atk: 7,
    def: 5,
    xpDrop: 7,
    drop: ["Золото", 10],
  },
  орк: {
    name: "Орк",
    hp: 70,
    MaxHp: 70,
    atk: 18,
    def: 10,
    xpDrop: 15,
    drop: ["орочий амулет"],
  },
  мимик: {
    name: "Мимик",
    hp: 100,
    MaxHp: 100,
    atk: 10,
    def: 20,
    xpDrop: 20,
    drop: ["драгоценость", "сундук"],
  },
  гарпия: {
    name: "Гарпия",
    hp: 45,
    MaxHp: 45,
    atk: 15,
    def: 5,
    xpDrop: 12,
    drop: ["перо гарпии"],
  },
  минотавр: {
    name: "Минотавр",
    hp: 120,
    MaxHp: 120,
    atk: 25,
    def: 15,
    xpDrop: 30,
    drop: ["рог минотавра"],
  },
  кобальт: {
    name: "Кобальт",
    hp: 35,
    MaxHp: 35,
    atk: 8,
    def: 4,
    xpDrop: 6,
    drop: ["чешуя кобальта"],
  },
  агрессивный_искатель: {
    name: "Агрессивный искатель",
    hp: 80,
    MaxHp: 80,
    atk: 20,
    def: 12,
    xpDrop: 25,
    drop: ["старый дневник"],
  },
  скелет: {
    name: "Скелет",
    hp: 60,
    MaxHp: 60,
    atk: 15,
    def: 8,
    xpDrop: 15,
    drop: ["кость", "ржавый щит"],
  },
  лич: {
    name: "Лич",
    hp: 110,
    MaxHp: 110,
    atk: 30,
    def: 10,
    xpDrop: 40,
    drop: ["магическая сфера"],
  },
  рыцарь_смерти: {
    name: "Рыцарь смерти",
    hp: 250,
    MaxHp: 250,
    atk: 45,
    def: 25,
    xpDrop: 150,
    drop: ["тяжелый доспех", "меч смерти"],
  },
};

if (typeof module !== "undefined") module.exports = vrag;
